// Generated by CoffeeScript 1.4.0
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.simplePanorama = {
    modules: {},
    isTouchDevice: function() {
      return !!(__indexOf.call(window, 'ontouchstart') >= 0);
    }
  };

}).call(this);
