// Generated by CoffeeScript 1.4.0

/*
  @depends bootstrap.js
  @depends ../vendor/modernizr.js
  @depends modules.js
*/


(function() {

  window.SimplePanorama = (function() {

    function SimplePanorama(options) {
      var imgFile, pano, wrapperElem;
      this.maxPos = 0;
      this.width = 0;
      this.elem = null;
      this.img = null;
      this.subElem = null;
      this.pos = 0.0;
      this.targetSpeed = 0;
      this.speed = 0;
      this.counter = 0;
      this.hsCounter = 0;
      this.isRepeative = null;
      this.moduleData = {};
      wrapperElem = options.elem;
      if ((!wrapperElem) && options.selector) {
        wrapperElem = $(options.selector);
      }
      if (!wrapperElem.length) {
        console.error('No DOM element supplied for panorama, use "elem" or "selector."');
        return null;
      }
      wrapperElem.append('<div class="sp-container"></div>');
      this.elem = wrapperElem.find('div.sp-container');
      imgFile = options.imagePath;
      if (!imgFile) {
        console.error('No image path supplied for panorama, use "imagePath".');
        return null;
      }
      this.isRepeative = options.repeative === void 0 ? true : options.repeative;
      if (!Modernizr.csstransforms3d) {
        this.updatePos = function() {
          return this.subElem.css("left", this.pos - this.img.width + "px");
        };
      }
      this.img = new Image;
      pano = this;
      this.img.onload = function() {
        var i, imgHtml, max, width, _i;
        pano.elem.css("height", this.height + "px");
        $(window).trigger("resize");
        imgHtml = "<div>";
        max = pano.isRepeative ? 2 : 0;
        for (i = _i = 0; 0 <= max ? _i <= max : _i >= max; i = 0 <= max ? ++_i : --_i) {
          imgHtml += "<img class=\"sp-image sp-number_" + i + "\" src=\"" + imgFile + "\" alt\"Panorama\" />";
        }
        pano.elem.html(imgHtml + "</div>");
        width = pano.img.width;
        pano.subElem = $(pano.elem.children()[0]);
        pano.subElem.css("width", width * (max + 1) + "px");
        if (pano.isRepeative) {
          pano.subElem.css("left", "-" + width + "px");
        }
        pano.lastTick = (new Date).getTime();
        pano.updateSpeedTicks = 0;
        window.setInterval((function() {
          return pano.updatePano();
        }), 1);
        pano.elem.mousedown(function(event) {
          return event.preventDefault();
        });
        pano.elem.attr("oncontextmenu", "return false;");
        if (options.modules) {
          $.each(options.modules, function(i, moduleId) {
            pano.moduleData[moduleId] = {};
            return simplePanorama.modules[moduleId](pano, pano.moduleData[moduleId]);
          });
        }
        return typeof options.callback === "function" ? options.callback() : void 0;
      };
      $(window).resize(function() {
        pano.width = pano.img.width < pano.elem.width() ? pano.img.width : pano.elem.parent().innerWidth();
        pano.elem.css("width", pano.width + "px");
        return pano.maxPos = pano.isRepeative ? pano.img.width : pano.img.width - pano.width;
      });
      this.img.src = imgFile;
    }

    SimplePanorama.prototype.updateSpeed = function() {
      return this.speed = (1.7 * this.speed + 0.3 * this.targetSpeed) / 2;
    };

    SimplePanorama.prototype.updatePano = function() {
      var newPos, passedTicks, ticks;
      ticks = new Date().getTime();
      passedTicks = ticks - this.lastTick;
      this.lastTick = ticks;
      this.updateSpeedTicks += passedTicks;
      if (this.updateSpeedTicks > 50) {
        this.updateSpeed();
        this.updateSpeedTicks = 0;
      }
      if (this.subElem !== null) {
        newPos = this.pos + this.speed * passedTicks;
        if (this.isRepeative) {
          newPos = newPos % this.maxPos;
        } else {
          if (newPos < 0) {
            newPos = 0;
          } else if (newPos > this.maxPos) {
            newPos = this.maxPos;
          }
        }
        this.pos = newPos;
        return this.updatePos();
      }
    };

    SimplePanorama.prototype.updatePos = function() {
      var pos, transform;
      pos = this.isRepeative ? this.pos : this.pos - this.maxPos;
      transform = "translate3D(" + pos + "px, 0, 0)";
      this.subElem.css("-o-transform", transform);
      this.subElem.css("-webkit-transform", transform);
      this.subElem.css("-moz-transform", transform);
      this.subElem.css("-ms-transform", transform);
      return this.subElem.css("transform", transform);
    };

    SimplePanorama.prototype.createCircleHotspot = function(content, x, y, r) {
      var hs;
      hs = this.prepareHotspot(content, "sp-circ", x - r, y - r, r * 2, r * 2);
      hs.css("border-radius", r + "px");
      return this.populateTripleBuffer(hs);
    };

    SimplePanorama.prototype.createRectHotspot = function(content, x, y, w, h) {
      var hs;
      hs = this.prepareHotspot(content, "sp-rect", x, y, w, h);
      return this.populateTripleBuffer(hs);
    };

    SimplePanorama.prototype.prepareHotspot = function(content, cssClass, x, y, w, h) {
      var result;
      this.subElem.append('<div class="sp-number-' + ++this.hsCounter + ' sp-hotspot ' + cssClass + '"><div class="sp-hotspot-content">' + content + '</div></div>');
      result = $(".sp-hotspot.sp-number-" + this.hsCounter);
      result.css("left", x + "px");
      result.css("top", y + "px");
      result.css("width", w + "px");
      result.css("height", h + "px");
      return result;
    };

    SimplePanorama.prototype.getRelativePos = function(pageX, pageY) {
      var result;
      result = new Object();
      result.x = Math.floor(pageX - this.elem.offset().left(+this.img.width - this.pos));
      result.x %= this.img.width;
      result.y = Math.floor(pageY - this.elem.offset().top);
      if (result.y < 0) {
        result.y = 0;
      }
      return result;
    };

    SimplePanorama.prototype.populateTripleBuffer = function(elem) {
      var c1, c2, left;
      if (this.isRepeative) {
        c1 = elem.clone();
        c2 = elem.clone();
        left = elem.position().left;
        c1.css("left", left + this.img.width + "px");
        c2.css("left", left + this.img.width * 2 + "px");
        c1.appendTo(this.subElem);
        return c2.appendTo(this.subElem);
      }
    };

    return SimplePanorama;

  })();

}).call(this);
